CREATE TABLE employees (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    position TEXT NOT NULL,
    wage DECIMAL NOT NULL,
    pin TEXT NOT NULL,
    isclockedin BOOlEAN DEFAULT FALSE NOT NULL,
    onbreak BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE timesheets (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,   
    shift_start TIMESTAMP DEFAULT now() NOT NULL,
    shift_end TIMESTAMP,
    onbreak TIMESTAMP,
    offbreak TIMESTAMP,
    date TIMESTAMP DEFAULT now() NOT NULL, 
    employee_id INTEGER REFERENCES employees(id) ON DELETE CASCADE NOT NULL
);

CREATE TABLE menu (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category TEXT NOT NULL
);

CREATE TABLE menuItems (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    price DECIMAL NOT NULL,
    menuid INTEGER REFERENCES menu(id) ON DELETE CASCADE NOT NULL
);

CREATE TABLE activeorders (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    orderitems TEXT NOT NULL,
    complete BOOLEAN DEFAULT FALSE NOT NULL
);

INSERT INTO employees
(first_name, last_name, position, wage, pin) 
VALUES 
('Admin', 'Admin', 'Admin', 20.00, '$2a$12$SCTJMHayQAaMOCfRsaN3a.g55VBUET/5IWsnj5xq52NGaifkZatLO'),
('Employee 1 fname', 'Employee 1 lname', 'General Manager', 15.00, '$2a$12$NgwQnQi79jW2e9C7.zWM3.jvviNp/GQcYqB7dob6FaGSySpmjWMRO'),
('Employee 2 fname', 'Employee 2 lname', 'Team Member', 12.00, '$2a$12$aGvFjE02IwKhD8XdPNlLNuILqM8uEaYu1DReH/o9ddYJJUrZc8xZy ');

INSERT INTO timesheets 
(employee_id) 
VALUES 
(1), 
(2), 
(3),
(2);

INSERT INTO menu 
(category) 
VALUES 
('Burgers'),
('Sides'),
('Drinks'),
('Salads');

/*Inserting Burgers into menuItems*/
INSERT INTO menuItems 
(name, price, menuId)
VALUES
('Whopper', 6.25, 1),
('Cheese Burger', 4.50, 1),
('Baconator', 7, 1),
('Double Stacker', 5.50, 1);

/*Inserting Side into menuItems*/
INSERT INTO menuItems
(name, price, menuId)
VALUES
('Fries', 2, 2),
('Mozzarella Sticks', 1.25, 2),
('Chicken Nuggets', 4.50, 2);

/*Inserting Drinks into menuItems*/
INSERT INTO menuItems
(name, price, menuId)
VALUES 
('Coke', 1, 3),
('Orange', 1, 3),
('Sprite', 1, 3);


/*Insertign salads into menuItems*/
INSERT INTO menuItems
(name, price, menuId)
VALUES 
('Chicken club Salad', 7, 4),
('Caeser Salad', 7.25, 4),
('Cob Salad', 6.75, 4);



INSERT INTO activeorders
(name, orderitems)
VALUES
('Jason', '{"{\"id\":1,\"name\":\"Whopper\",\"price\":\"6.25\",\"menuid\":1}"}'),
('Max', '{"{\"id\":1,\"name\":\"Whopper\",\"price\":\"6.25\",\"menuid\":1}"}');