CREATE TABLE employees (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    position TEXT NOT NULL,
    wage DECIMAL NOT NULL,
    todaysHours DECIMAL DEFAULT 0.00 NOT NULL,
    pin INTEGER NOT NULL,
    isClockIn BOOlEAN DEFAULT FALSE NOT NULL,
    onBreak BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE timesheets (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,           
    hours DECIMAL DEFAULT 0.00 NOT NULL,
    shift_start TIMESTAMP DEFAULT now() NOT NULL,
    shift_end TIMESTAMP,
    went_on_break BOOLEAN DEFAULT FALSE NOT NULL,
    break_clock_out TIMESTAMP,
    break_clock_in TIMESTAMP,
    date TIMESTAMP DEFAULT now() NOT NULL, 
    employee_id INTEGER REFERENCES employees(id) ON DELETE CASCADE NOT NULL
);

CREATE TABLE menu (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category TEXT NOT NULL
);

CREATE TABLE menuItems (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    price DECIMAL NOT NULL,
    menuid INTEGER REFERENCES menu(id) ON DELETE CASCADE NOT NULL
);

INSERT INTO employees
(first_name, last_name, position, wage, pin) 
VALUES 
('Admin', 'Admin', 'Admin', 20.00, 1111),
('Employee 1 fname', 'Employee 1 lname', 'General Manager', 15.00, 2222),
('Employee 2 fname', 'Employee 2 lname', 'Team Member', 12.00, 3333);

INSERT INTO timesheets 
(hours, employee_id) 
VALUES 
(35, 1), 
(20, 2), 
(12, 3);

INSERT INTO menu 
(category) 
VALUES 
('Burgers'),
('Sides'),
('Drinks'),
('Salads');

/*Inserting Burgers into menuItems*/
INSERT INTO menuItems 
(name, price, menuId)
VALUES
('Whopper', 6.25, 1),
('Cheese Burger', 4.50, 1),
('Baconator', 7, 1),
('Double Stacker', 5.50, 1);

/*Inserting Side into menuItems*/
INSERT INTO menuItems
(name, price, menuId)
VALUES
('Fries', 2, 2),
('Mozzarella Sticks', 1.25, 2),
('Chicken Nuggets', 4.50, 2);

/*Inserting Drinks into menuItems*/
INSERT INTO menuItems
(name, price, menuId)
VALUES 
('Coke', 1, 3),
('Orange', 1, 3),
('Sprite', 1, 3);


/*Insertign salads into menuItems*/
INSERT INTO menuItems
(name, price, menuId)
VALUES 
('Chicken club Salad', 7, 4),
('Caeser Salad', 7.25, 4),
('Cob Salad', 675, 4);



